# Generated by Django 3.1 on 2020-08-24 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200824_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='zipcode',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(99999)]),
        ),
    ]
