# Generated by Django 3.1 on 2020-08-24 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200824_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='zipcode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
