# Generated by Django 3.1 on 2020-08-24 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200824_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[:alpha:]')]),
        ),
    ]
