# Generated by Django 3.1 on 2020-08-24 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200824_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='lastname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[:alpha:]')]),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[:alpha:]')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='city',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[:alpha:]')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='lastname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[:alpha:]')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='state',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[:alpha:]')]),
        ),
    ]
